const series=[
['One Piece','Ongoing','assets/series/one-piece.jpg'],['Mushoku Tensei: Jobless Reincarnation','14 Episodes','assets/series/mushoku-tensei.jpg'],['Re:ZERO - Starting Life in Another World','19 Episodes','assets/series/rezero.jpg'],['Daemons of the Shadow Realm','24 Episodes','assets/series/daemons-shadow.jpg'],['That Time I Got Reincarnated as a Slime','Ongoing','assets/series/slime.jpg'],['Solo Leveling','25 Episodes','assets/series/solo-leveling.jpg'],['Demon Slayer','63 Episodes','assets/series/demon-slayer.jpg'],['Jujutsu Kaisen','47 Episodes','assets/series/jujutsu-kaisen.jpg'],['Naruto','220 Episodes','assets/series/naruto.jpg'],['Bleach','366 Episodes','assets/series/bleach.jpg'],['Attack on Titan','89 Episodes','assets/series/aot.jpg'],['My Hero Academia','159 Episodes','assets/series/mha.jpg'],['Black Clover','170 Episodes','assets/series/black-clover.jpg'],['Dragon Ball Super','131 Episodes','assets/series/dbs.jpg'],['Hunter x Hunter','148 Episodes','assets/series/hxh.jpg'],['Death Note','37 Episodes','assets/series/death-note.jpg'],['One Punch Man','24 Episodes','assets/series/opm.jpg'],['Dandadan','24 Episodes','assets/series/dandadan.jpg'],['Pokemon','Ongoing','assets/series/pokemon.jpg'],['Frieren','28 Episodes','assets/series/frieren.jpg']];

const movies=[
['Pokémon: Arceus and the Jewel of Life','Movie','assets/movies/pokemon-arceus.jpg'],['Metal Fight Beyblade','Movie','assets/movies/beyblade.jpg'],['Pokémon Ranger and the Temple of Sea','Movie','assets/movies/pokemon-ranger.jpg'],['Pokémon the Movie: Secrets of the Jungle','Movie','assets/movies/secrets-jungle.jpg'],['A Silent Voice','★ 8.8','assets/movies/a-silent-voice.jpg'],['Your Name','★ 8.6','assets/movies/your-name.jpg'],['Demon Slayer - Mugen Train','★ 8.4','assets/movies/mugen-train.jpg'],['Spirited Away','★ 8.6','assets/movies/spirited-away.jpg'],['Jujutsu Kaisen 0','★ 8.3','assets/movies/jjk0.jpg'],['Weathering With You','★ 8.2','assets/movies/weathering.jpg'],['Suzume','★ 8.0','assets/movies/suzume.jpg'],["Howl's Moving Castle",'★ 8.7','assets/movies/howls.jpg'],['The Boy and the Heron','★ 7.4','assets/movies/heron.jpg'],['Dragon Ball Super: Broly','★ 7.7','assets/movies/dbs-broly.jpg'],['One Piece Film Red','★ 7.2','assets/movies/one-piece-red.jpg'],['My Hero Academia: Heroes Rising','★ 7.8','assets/movies/mha-heroes.jpg'],['Naruto: The Last','★ 6.9','assets/movies/naruto-last.jpg'],['Boruto: Naruto the Movie','★ 6.7','assets/movies/boruto.jpg'],['Ponyo','★ 7.6','assets/movies/ponyo.jpg'],['Wolf Children','★ 8.0','assets/movies/wolf-children.jpg']];

const cartoons=[
['Pokemon','Cartoon','assets/cartoon/pokemon.jpg'],['Ben 10','Cartoon','assets/cartoon/ben10.jpg'],['Doraemon','Cartoon','assets/cartoon/doraemon.jpg'],['Shinchan','Cartoon','assets/cartoon/shinchan.jpg'],['Tom and Jerry','Cartoon','assets/cartoon/tom-jerry.jpg'],['Ninja Hattori','Cartoon','assets/cartoon/ninja-hattori.jpg'],['Kiteretsu','Cartoon','assets/cartoon/kiteretsu.jpg'],['Perman','Cartoon','assets/cartoon/perman.jpg'],['Oggy and the Cockroaches','Cartoon','assets/cartoon/oggy.jpg'],['Motu Patlu','Cartoon','assets/cartoon/motu-patlu.jpg'],['Chhota Bheem','Cartoon','assets/cartoon/chhota-bheem.jpg'],['Courage the Cowardly Dog','Cartoon','assets/cartoon/courage.jpg'],['Scooby-Doo','Cartoon','assets/cartoon/scooby.jpg'],['Dragon Ball','Cartoon','assets/cartoon/dragon-ball.jpg'],['Transformers','Cartoon','assets/cartoon/transformers.jpg'],['Teen Titans','Cartoon','assets/cartoon/teen-titans.jpg'],['Dora the Explorer','Cartoon','assets/cartoon/dora.jpg'],['Mr. Bean','Cartoon','assets/cartoon/mr-bean.jpg'],['Power Rangers','Cartoon','assets/cartoon/power-rangers.jpg'],['Looney Tunes','Cartoon','assets/cartoon/looney-tunes.jpg']];

function cards(list){return list.map(x=>`<article class="card"><img src="${x[2]}" alt="${x[0]}" loading="lazy" onerror="this.src='assets/no-image.jpg'"><div class="info"><b>${x[0]}</b><span>${x[1]}</span></div></article>`).join('')}
function put(id,list){document.getElementById(id).innerHTML=cards(list)}
put('series',series);put('movies',movies);put('cartoons',cartoons);put('popular',movies.slice(4,14));

document.getElementById('clear').onclick=()=>{localStorage.removeItem('history');document.getElementById('history').textContent='Your watch history will appear here.'};
document.getElementById('search').onsubmit=e=>{e.preventDefault();const q=document.getElementById('q').value.trim().toLowerCase();if(!q)return;const all=[...series,...movies,...cartoons].filter(x=>x[0].toLowerCase().includes(q));put('series',all);document.getElementById('series').scrollIntoView({behavior:'smooth'});}
