const seriesGrid=document.getElementById('seriesGrid'),movieGrid=document.getElementById('movieGrid'),cartoonGrid=document.getElementById('cartoonGrid'),popularGrid=document.getElementById('popularGrid');
const esc=v=>String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function card(x,type){return `<article class="poster"><div class="poster-img"><img src="${x.image||'https://placehold.co/500x700/151721/fff?text=No+Image'}" alt="${esc(x.title)}" loading="lazy"><span class="badge">${type}</span></div><div class="poster-body"><div class="poster-title">${esc(x.title)}</div><div class="poster-meta">${esc(x.meta||type)}<br>★ ${x.rating||'N/A'}</div></div></article>`}
async function loadAnime(){try{let r=await fetch('https://api.jikan.moe/v4/top/anime?limit=12'),d=await r.json();let a=(d.data||[]).map(x=>({title:x.title,image:x.images?.jpg?.large_image_url,meta:x.type||'Anime',rating:x.score||'N/A'}));seriesGrid.innerHTML=a.map(x=>card(x,'HD')).join('');popularGrid.innerHTML=a.slice(0,8).map(x=>card(x,'Movie')).join('')}catch(e){seriesGrid.innerHTML='<div class="loading">Anime could not be loaded. Refresh once.</div>'}}
async function loadCartoons(){let names=['Pokemon','Ben 10','Doraemon','Shinchan','Tom and Jerry','Transformers'],out=[];await Promise.all(names.map(async n=>{try{let r=await fetch('https://api.tvmaze.com/search/shows?q='+encodeURIComponent(n)),d=await r.json();let s=d[0]?.show;if(s)out.push({title:n,image:s.image?.original||s.image?.medium,meta:'Cartoon'})}catch(e){}}));cartoonGrid.innerHTML=out.map(x=>card(x,'Cartoon')).join('')}
function makeMovies(){let m=[['A Silent Voice','https://placehold.co/500x700/172a3a/fff?text=A+Silent+Voice','8.8'],['Your Name','https://placehold.co/500x700/102a4a/fff?text=Your+Name','8.6'],['Demon Slayer','https://placehold.co/500x700/301018/fff?text=Demon+Slayer','8.4'],['Spirited Away','https://placehold.co/500x700/24352a/fff?text=Spirited+Away','8.6'],['Jujutsu Kaisen 0','https://placehold.co/500x700/172039/fff?text=Jujutsu+Kaisen+0','8.3']];movieGrid.innerHTML=m.map(x=>card({title:x[0],image:x[1],meta:'Movie',rating:x[2]},'Movie')).join('')}
function focusSearch(){document.getElementById('searchInput').focus();scrollTo({top:0,behavior:'smooth'})}
function searchSite(){let q=document.getElementById('searchInput').value.trim().toLowerCase();document.querySelectorAll('.poster').forEach(p=>p.style.display=!q||p.innerText.toLowerCase().includes(q)?'block':'none')}
document.getElementById('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')searchSite()});
function clearHistory(){document.getElementById('historyGrid').innerHTML='<div class="empty-state">Your watch history will appear here.</div>'}
makeMovies();loadAnime();loadCartoons();