const API='https://graphql.anilist.co';
async function api(query,variables={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,variables})});if(!r.ok)throw Error('API');return (await r.json()).data}
function safe(s=''){return s.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]))}
function card(x,type='Series'){const e=document.createElement('article');e.className='poster';e.innerHTML=`<img src="${x.image}" alt="${safe(x.title)}" onerror="this.src='https://placehold.co/400x600/111/fff?text=No+Image'"><div class="poster-title">${safe(x.title)}</div><div class="poster-meta">${type==='Movie'?'Movie':(x.episodes?x.episodes+' Episodes':'Ongoing')}</div>`;e.onclick=()=>saveHistory(x,type);return e}
async function loadSeries(){const b=document.getElementById('series');try{const d=await api(`query{Page(page:1,perPage:12){media(type:ANIME,sort:POPULARITY_DESC,status:RELEASING){title{romaji english}episodes coverImage{large}}}}`);b.innerHTML='';d.Page.media.forEach(a=>b.appendChild(card({title:a.title.english||a.title.romaji,image:a.coverImage.large,episodes:a.episodes})));}catch(e){b.innerHTML='<div class="empty">Refresh to load series.</div>'}}
async function loadMovies(){const b=document.getElementById('movies');try{const d=await api(`query{Page(page:1,perPage:12){media(type:ANIME,format:MOVIE,sort:POPULARITY_DESC){title{romaji english}coverImage{large}}}}`);b.innerHTML='';d.Page.media.forEach(a=>b.appendChild(card({title:a.title.english||a.title.romaji,image:a.coverImage.large},'Movie')))}catch(e){b.innerHTML='<div class="empty">Refresh to load movies.</div>'}}
const cartoons=['Pokemon','Ben 10','Doraemon','Shin-chan','Dragon Ball'];
async function loadCartoons(){const b=document.getElementById('cartoons');b.innerHTML='';for(const n of cartoons){try{const r=await fetch('https://api.tvmaze.com/singlesearch/shows?q='+encodeURIComponent(n));const s=await r.json();b.appendChild(card({title:s.name,image:s.image?.original||s.image?.medium},'Cartoon'))}catch(e){b.appendChild(card({title:n,image:'https://placehold.co/400x600/111/fff?text='+encodeURIComponent(n)},'Cartoon'))}}}
async function searchCards(){const v=document.getElementById('searchInput').value.trim();if(!v){loadSeries();loadMovies();return}const d=await api(`query($s:String){Page(page:1,perPage:20){media(search:$s,type:ANIME){title{romaji english}episodes format coverImage{large}}}}`,{s:v});document.getElementById('series').innerHTML='';document.getElementById('movies').innerHTML='';d.Page.media.forEach(a=>{const t=a.format==='MOVIE'?'movies':'series';document.getElementById(t).appendChild(card({title:a.title.english||a.title.romaji,image:a.coverImage.large,episodes:a.episodes},a.format==='MOVIE'?'Movie':'Series'))})}
function focusSearch(){document.getElementById('searchInput').focus();window.scrollTo({top:0,behavior:'smooth'})}
function toggleMenu(){alert('Pratik Anime Stream')}
function saveHistory(x,type){let a=JSON.parse(localStorage.getItem('pratikHistory')||'[]').filter(y=>y.title!==x.title);a.unshift({...x,type});localStorage.setItem('pratikHistory',JSON.stringify(a.slice(0,8)));showHistory()}
function showHistory(){const b=document.getElementById('history'),a=JSON.parse(localStorage.getItem('pratikHistory')||'[]');b.innerHTML=a.length?'':'<div class="empty">Your watch history will appear here.</div>';a.forEach(x=>b.appendChild(card(x,x.type||'Series')))}
function clearHistory(){localStorage.removeItem('pratikHistory');showHistory()}
document.addEventListener('DOMContentLoaded',()=>{loadSeries();loadMovies();loadCartoons();showHistory();document.getElementById('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')searchCards()})});